# Настройка серверного приложения
[server]
# Порт для прослушивания клиентских соединений
listening_port = 1234

# Информация об используемом сертификате (для использования асинхронного шифрования)
[security]
# По умолчанию для хранения сертификата и закрытого ключа создаётся директория certificate
path_to_private_key="certificate/"
path_to_certificate="certificate/"
# Код, который вводился во время создания сертификата
pass_phrase=""

[database]
name = "besmesdb"
host_address = "127.0.0.1"
# Порт, прослушиваемый Postgresql по умолчанию
listening_port = 5432

# Настройка подключения к базе данных
[database_connection]
user_name = ""
password = ""
