# Настройка серверного приложения
[server]
# ВАЖНО: должны быть указаны разные порты!
# Порт для прослушивания клиентских соединений
client_connection_port = 0
# Порт для прослушивания администраторских соединений
admin_connection_port = 0

# Настрока аккаунта супер-пользователя
[super_user]
login = ""
password = ""

[database]
address = "127.0.0.1"
# По умолчанию MySql Server прослушивает именно этот порт
port = 3306

# Настройка подключения к базе данных
[database_connection]
user_name = ""
password = ""

# Настройка системы email-оповещений
[esmtp_server]
# Адрес smtp-сервера, который будет ответственен за отправку сообщений. По умолчанию используем сервер компании Google
# ВАЖНО: необходимо, чтобы домен сервера и домен адреса почты совпадали, иначе сообщения отправляться не будут
address = "smtp.gmail.com"
port = 465

# Информация об электронной почте, с которой пользователям будут отправляться уведомления.
# Учтите, что в настройках аккаунта должна быть снята пометка о "безопасных источниках".
# Иначе с помощью esmtp-протокола не получится отправлять сообщения
[email_sender_account]
email = ""
password = ""

# Заголовок и тело уведомления о регистрации
[registration_notification]
title = "Регистрация в системе BesMes"
# %1 - имя пользователя, %2 - код регистрации.
body = 
'''
Привет, %1!, 
Ваша почта была использована для регистрации аккаунта в системе BesMes!
Если не вы отправили запрос, проигнорируйте письмо.
Ваш код регистрации: %2.

С уважением, 
команда разработки системы BesMes!
'''